config/routes.rb
Rails.application.routes.draw do
  resources :levels do
      collection do
          get 'new/input', to: "levels#ajax_input"
          get 'new/output', to: "levels#ajax_output"
      end
  end
  resources :users, except: [:edit, :update, :delete, :create, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "application#root"
  get "/oauth", to: "application#oauth", as: :oauth
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/level.rb
class Level < ApplicationRecord
	belongs_to :user
	validates :JSONinputs, :JSONoutputs, :JSONpieces, :width, :height, presence: true
	validates :width, :height, numericality: { only_integer: true, greater_than: 0 }
	[:inputs, :outputs, :pieces].each do |method|
		define_method method do
			if result = self.send("JSON#{method}")
				return JSON.parse(result)
			end
		end
		define_method "#{method}=" do |arg|
			raise "Wrong type" if !arg.kind_of? Array
			self.send("JSON#{method}=", arg.to_json)
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :levels

	def self.from_oauth(info)
		u = self.find_or_create_by(gid: info['id'])
		info.slice(
			'email',
			'given_name',
			'family_name',
			'link',
			'picture'
		).each do |k,v|
			u.send "#{k}=", v
		end
		u.save
		return u
	end

	def name
		if self.given_name.blank?
			return self.family_name
		elsif self.family_name.blank?
			return self.given_name
		else
			return "#{self.given_name} #{self.family_name}"
		end
	end

	def picture_scale(size = 512)
		return self.picture.gsub(/\/photo\.jpg$/, "/s#{size.to_s}-c-mo/photo.jpg")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
	require 'signet/oauth_2/client'
	require 'json'
	require 'open-uri'
	protect_from_forgery with: :exception
	before_action :login, except: [:root, :oauth]
	helper_method :current_user, :logged_in?
	# No layout for ajax
	layout proc{|c| c.request.xhr? ? false : "application" }

	def oauth
		client_init
		@client.code = params['code']
		c = @client.fetch_access_token!
		url = "https://www.googleapis.com/oauth2/v1/userinfo?access_token=#{c['access_token']}"
		login_with JSON.parse open(url).read
		if session[:redirect].present?
			redirect_to session[:redirect]
		else
			redirect_to root_path
		end
	end

	def root
		if logged_in?
			redirect_to levels_path
		else
			render file: "content/main", layout: false
		end
	end

	private

	def login
		unless logged_in?
			session[:redirect] = request.original_url
			client_init
			redirect_to(@client.authorization_uri.to_s)
		end
	end

	def login_with(info)
		@current_user = User.from_oauth info
		session[:user_id] = @current_user.id
	end

	def client_init
		@client = Signet::OAuth2::Client.new(
			:authorization_uri => 'https://accounts.google.com/o/oauth2/auth',
			:token_credential_uri =>  'https://www.googleapis.com/oauth2/v4/token',
			:redirect_uri => oauth_url,
			:scope => 'email profile',
			# Client info from Google API console
			:client_id => '831933960744-ltmis3dsek2sn9727ndfmik9fuklg3a4.apps.googleusercontent.com',
			:project_id => 'trubool-150412',
			:auth_provider_x509_cert_url => 'https://www.googleapis.com/oauth2/v1/certs',
			:client_secret => 'sYtRDzWlgUKWNNTlaZjyatsl'
		)
	end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
	before_action :set_level, only: [:show, :edit, :update, :destroy]
	before_action :only_creator, only: [:edit, :update, :destroy]

	# GET /levels
	# GET /levels.json
	def index
		@levels = Level.all
	end

	# GET /levels/1
	# GET /levels/1.json
	def show
		render layout: false
	end

	# GET /levels/new
	def new
		@level = Level.new
	end

	# GET /levels/1/edit
	def edit
	end

	# POST /levels
	# POST /levels.json
	def create
		@level = Level.new(level_params.merge(user_id: current_user.id))

		respond_to do |format|
			if @level.save
				format.html { redirect_to @level, notice: 'Level was successfully created.' }
				format.json { render :show, status: :created, location: @level }
			else
				format.html { render :new }
				format.json { render json: @level.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /levels/1
	# PATCH/PUT /levels/1.json
	def update
		respond_to do |format|
			if @level.update(level_params)
				format.html { redirect_to @level, notice: 'Level was successfully updated.' }
				format.json { render :show, status: :ok, location: @level }
			else
				format.html { render :edit }
				format.json { render json: @level.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /levels/1
	# DELETE /levels/1.json
	def destroy
		@level.destroy
		respond_to do |format|
			format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def ajax_input
		render "_input", layout: false
	end

	def ajax_output
		render "_output", layout: false
	end

	private

	def only_creator
		redirect_back fallback_location: levels_path, alert: "Only editable by the current user" if current_user != @level.user
	end

	# Use callbacks to share common setup or constraints between actions.
	def set_level
		@level = Level.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def level_params
		p = params.require(:level).permit(:user_id, :pieces, :width, :height, :name, :description, :inputs => [], :outputs => [])
		# p[:outputs] = p[:outputs].map { |a| a.split('') }
		# p[:inputs] = p[:inputs].map { |a| a.split('') }
		p[:pieces] = p[:pieces].split(',')
		# raise p.inspect
		p
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show]

	# GET /users
	# GET /users.json
	def index
		@users = User.all
	end

	# GET /users/1
	# GET /users/1.json
	def show
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
		@user = User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:user).permit(:name, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# $user_id is for testing
	def logged_in?
		return session[:user_id].present? || $user_id.present?
	end

	def current_user
		if logged_in?
			return @current_user ||= User.find(session[:user_id] || $user_id)
		else
			return nil
		end
	end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/content/_styles.html.erb
<!-- File for polymer component styling -->
<link rel="import" href="/components/paper-styles/paper-styles.html">
<style is="custom-style">
#login-button {
    display: table;
    margin: 0 auto 2em auto;
    text-decoration: none;
}

#login-button paper-button {
    color: rgba(0, 0, 0, 0.54);
    background: white;
    white-space: nowrap;
    text-transform: none;
    text-decoration: none;
    font-weight: bold;
    cursor: pointer;
}
 #login-button iron-icon {
     margin-right: 1em;
 }
</style>

app/views/content/main.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
		<title>TruBool</title>
		<%= csrf_meta_tags %>
		<meta name="theme-color" content="#000">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<script src="/components/webcomponentsjs/webcomponents.min.js"></script>
		<link rel="import" href="/components/iron-icons/iron-icons.html">

		<link rel="import" href="/components/paper-icon-button/paper-icon-button.html">
		<link rel="import" href="/components/paper-item/paper-item.html">
		<link rel="import" href="/components/paper-listbox/paper-listbox.html">
		<link rel="import" href="/components/paper-button/paper-button.html">

		<link rel="import" href="/components/app-layout/app-drawer-layout/app-drawer-layout.html">
		<link rel="import" href="/components/app-layout/app-drawer/app-drawer.html">
		<link rel="import" href="/components/app-layout/app-header-layout/app-header-layout.html">
		<link rel="import" href="/components/app-layout/app-header/app-header.html">
		<link rel="import" href="/components/app-layout/app-toolbar/app-toolbar.html">
		<link rel="import" href="/components/app-layout/app-scroll-effects/app-scroll-effects.html">

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render "content/app-icons" %>
		<%= render "layouts/styles" %>
		<%= render "content/styles" %>
		<style is="custom-style">
			#menu-toggle {
				color: white;
				--paper-icon-button-ink-color: white;
				margin: 10px;
				position: fixed;
				top: 0px;
				left: 0px;
			}
		</style>
	</head>
	<body>
		<app-drawer-layout responsive-width="1280px">
			<app-drawer id="drawer" swipe-open>
				<%= render "layouts/drawercontent" %>
			</app-drawer>
			<!-- main panel -->
			<paper-icon-button id="menu-toggle" icon="menu" drawer-toggle></paper-icon-button>
			<%= image_tag "Head.svg", style: "width: 100%; height: auto;" %>
			<%= link_to levels_path, id: "login-button" do %>
				<paper-button raised><iron-icon icon="app:google-g"></iron-icon> Sign in with Google</paper-button>
			<% end %>
		</app-drawer-layout>
	</body>
</html>

app/views/layouts/_drawercontent.html.erb
<!-- nav panel -->
<app-header-layout id="drawer" has-scrolling-region>
	<% if logged_in? %>
		<app-header fixed>
			<div class="avatar-container">
				<div class="image"></div>
			</div>
			<div class="contact-info">
				<div class="name"><%= current_user.name %></div>
				<div class="email"><%= current_user.email %></div>
			</div>
		</app-header>
	<% end %>
	<!-- nav menu -->
	<paper-listbox>
		<%= link_to levels_path do %>
			<paper-item>
				Home
				<paper-ripple></paper-ripple>
			</paper-item>
		<% end %>
		<%= link_to users_path do %>
			<paper-item>
				Users
				<paper-ripple></paper-ripple>
			</paper-item>
		<% end %>
		<%= link_to current_user, remote: true do %>
			<paper-item>
				Profile
				<paper-ripple></paper-ripple>
			</paper-item>
		<% end %>
	</paper-listbox>

	<footer>
		<a href="https://github.com/BrandonRoehl/TruBool/issues" target="_blank">
			<paper-button raised>
				Issue
			</paper-button>
		</a>
		<br />
		&copy; Brandon Roehl
	</footer>
</app-header-layout>

app/views/layouts/_styles.html.erb
<!-- File for polymer component styling -->
<link rel="import" href="/components/paper-styles/paper-styles.html">
<%= render "layouts/theme" %>
<style is="custom-style">
	paper-button[raised] {
		color: white;
		margin: 10px;
		background: var(--primary-color);
		white-space: nowrap;
	}

	app-header.main {
		color: #fff;
		background-color: var(--primary-color);
	}

	app-toolbar {
		height: 120px;
	}

	[condensed-title] {
		position: absolute;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		background-repeat: no-repeat;
		background-position: center center;
		background-size: 250px;

		/* The difference in font size is used to calculate the scale of the title in the transition. */
		font-size: 16px;
	}

	[main-title] {
		position: absolute;
		top: -120px;
		bottom: 0;
		left: 0;
		right: 0;
		background-repeat: no-repeat;
		background-position: center center;
		background-size: 425px;
		-webkit-transform-origin: center top !important;
		transform-origin: center top !important;

		/* The difference in font size is used to calculate the scale of the title in the transition. */
		font-size: 32px;
	}


	.content {
		display: block;
		position: relative;
		max-width: 1000px;
		margin: 5px auto;
	}

	.card-container {
		display: inline-block;
		width: 33.33%;
		color: black;
		text-decoration: none;
	}

	paper-card {
		display: block;
		margin: 5px;

		--paper-card-header-image: {
			height: 200px;
		}
	}

	paper-card h2 {
		margin: 4px;
		font-weight: normal;
	}

	paper-card p {
		margin: 4px;
		color: #999;
	}

	@media (max-width: 960px) {
		.content {
			max-width: 800px;
		}

		.card-container {
			width: 50%;
		}
	}

	@media (max-width: 719px) {
		app-toolbar {
			height: 60px;
		}

		[condensed-title] {
			background-size: 100px;
		}

		[main-title] {
			top: -60px;
			background-size: 225px;
		}

		.content {
			max-width: 400px;
		}

		.card-container {
			width: 100%;
		}
	}

	.avatar-container {
		position: relative;
		height: 90px;
		padding: 2px;
		width: 90px;
		margin: 20px auto;
	}

	.contact-info {
		margin: 0 20px;
		padding-bottom: 20px;
		border-bottom: 1px solid #CCC;
		text-align: center;
	}

	.contact-info .name {
		font-weight: bold;
	}

	.contact-info .email {
		color: #999;
	}

	paper-item {
		@apply(--layout-center-center);
		height: 54px;
	}

	app-toolbar paper-icon-button {
		--paper-icon-button-ink-color: white;
	}

	<%= "
	[condensed-title] {
		background-image: url('#{ asset_path "Header-s.svg" }');
	}
	[main-title] {
		background-image: url('#{ asset_path "Header-l.svg" }');
	}
	".html_safe %>
<% if logged_in? && current_user.picture.present? %>
	<%= ".avatar-container .image {
		background-image: url('#{current_user.picture_scale 90}');
		background-size: contain;
		border-radius: 50%; height: 100%;
		width: 100%;}".html_safe %>
<% end %>

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
		<title>TruBool</title>
		<%= csrf_meta_tags %>
		<meta name="theme-color" content="#1976D2">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		<script src="/components/webcomponentsjs/webcomponents.min.js"></script>
		<link rel="import" href="/components/iron-icons/iron-icons.html">

		<link rel="import" href="/components/paper-icon-button/paper-icon-button.html">
		<link rel="import" href="/components/paper-button/paper-button.html">
		<link rel="import" href="/components/paper-item/paper-item.html">
		<link rel="import" href="/components/paper-listbox/paper-listbox.html">

		<link rel="import" href="/components/app-layout/app-drawer-layout/app-drawer-layout.html">
		<link rel="import" href="/components/app-layout/app-drawer/app-drawer.html">
		<link rel="import" href="/components/app-layout/app-header-layout/app-header-layout.html">
		<link rel="import" href="/components/app-layout/app-header/app-header.html">
		<link rel="import" href="/components/app-layout/app-toolbar/app-toolbar.html">
		<link rel="import" href="/components/app-layout/app-scroll-effects/app-scroll-effects.html">

		<link rel="import" href="/components/paper-fab/paper-fab.html">
		<link rel="import" href="/components/paper-card/paper-card.html">
		<link rel="import" href="/components/paper-dialog/paper-dialog.html">
		<link rel="import" href="/components/paper-dialog-scrollable/paper-dialog-scrollable.html">

		<%# <link rel="import" href="/components/neon-animation/animations/scale-up-animation.html"> %>
		<%# <link rel="import" href="/components/neon-animation/animations/fade-out-animation.html"> %>
		<!-- <link rel="manifest" href="/manifest.json"> -->
		<%= render "layouts/styles" %>
	</head>
	<body>
		<app-drawer-layout responsive-width="1280px">
			<app-drawer id="drawer" swipe-open>
				<%= render "layouts/drawercontent" %>
			</app-drawer>
			<!-- main panel -->
			<app-header-layout>
				<app-header class="main" effects="resize-title" condenses fixed shadow>
					<app-toolbar class="top-toolbar">
						<paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
						<div condensed-title></div>
					</app-toolbar>
					<app-toolbar class="bottom-toolbar">
						<div main-title></div>
					</app-toolbar>
				</app-header>
				<div class="content">
					<%= yield %>
				</div>
			</app-header-layout>
		</app-drawer-layout>
		<paper-dialog id="dialog" with-backdrop>
			<paper-dialog-scrollable>
				<div id="dialogContent"></div>
			</paper-dialog-scrollable>
			<div class="buttons">
				<paper-button dialog-dismiss>Close</paper-button>
			</div>
		</paper-dialog>
	</body>
</html>

app/views/layouts/drawer.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
        <title>TruBool</title>
        <%= csrf_meta_tags %>
        <meta name="theme-color" content="#000">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <script src="/components/webcomponentsjs/webcomponents.min.js"></script>
        <link rel="import" href="/components/iron-icons/iron-icons.html">

        <link rel="import" href="/components/paper-icon-button/paper-icon-button.html">
        <link rel="import" href="/components/paper-item/paper-item.html">
        <link rel="import" href="/components/paper-listbox/paper-listbox.html">

        <link rel="import" href="/components/app-layout/app-drawer-layout/app-drawer-layout.html">
        <link rel="import" href="/components/app-layout/app-drawer/app-drawer.html">
        <link rel="import" href="/components/app-layout/app-header-layout/app-header-layout.html">
        <link rel="import" href="/components/app-layout/app-header/app-header.html">
        <link rel="import" href="/components/app-layout/app-toolbar/app-toolbar.html">
        <link rel="import" href="/components/app-layout/app-scrollpos-control/app-scrollpos-control.html">
        <!-- <link rel="manifest" href="/manifest.json"> -->
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render "shared/styles" %>
    </head>
    <body>
        <app-drawer-layout>
            <app-drawer id="drawer" swipe-open>
                <%= render "layouts/drawercontent" %>
            </app-drawer>
            <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
            <%= yield %>
        </app-drawer-layout>
    </body>
</html>

app/views/levels/_form.html.erb
<%= javascript_include_tag 'level_form', 'data-turbolinks-track': 'reload' %>
<link rel="import" href="/components/paper-input/all-imports.html">
<link rel="import" href="/components/paper-fab/paper-fab.html">
<link rel="import" href="/components/paper-button/paper-button.html">
<style>
#level_height {
    float: right;
}

#level_height, #level_width {
    width: 47%;
    /* padding-right: 2%; */
    display: inline-block;
}
</style>
<%= form_for(level) do |f| %>
  <% if level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>
      <ul>
      <% level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <paper-input label="Name" id="level_name" value="<%= level.name %>" name="level[name]" auto-validate required></paper-input>

  <h3>Size</h3>
  <paper-input label="Width" id="level_width" value="<%= level.width %>" name="level[width]" type="number" auto-validate required>
      <div suffix>units</div>
  </paper-input>
  <paper-input label="Height" id="level_height" value="<%= level.height %>" name="level[height]" type="number" auto-validate required>
      <div suffix>units</div>
  </paper-input>

  <%# Need a nested form for the inputs and outputs  %>
  <%# Save as an inline hash  %>
  <h3>Inputs</h3>
  <div id="inputs">
      <% for input in @level.inputs %>
          <%= render partial: "input", locals: {input: input} %>
      <% end %>
  </div>
  <paper-fab mini icon="add" onclick="addInput()"></paper-fab>

  <h3>Outputs</h3>
  <div id="outputs">
      <% for output in @level.outputs %>
          <%= render partial: "output", locals: {output: output} %>
      <% end %>
  </div>
  <paper-fab mini icon="add" onclick="addOutput()"></paper-fab>

  <paper-input label="Pieces" id="level_pieces" value="<%= @level.pieces.join(',') %>" name="level[pieces]" allowed-pattern="[0-9,]" auto-validate required></paper-input>

  <paper-textarea label="Description" id="level_description" value="<%= level.description %>" name="level[description]"></paper-textarea>

  <div class="actions">
      <%= button_tag(type: 'submit', is: "paper-button", style: "background-color: transparent; border-color: transparent; padding:0;") do %>
          <paper-button raised style="font-size: 1.5em;">
              Save
          </paper-button>
      <% end %>
  </div>
<% end %>

app/views/levels/_game-styles.html.erb
<style is="custom-style">
	#menu-toggle {
		color: white;
		--paper-icon-button-ink-color: white;
		margin: 10px;
		position: fixed;
		top: 0px;
		left: 0px;
	}
</style>

app/views/levels/_input.html.erb
<paper-input label="Input" id="level_input" value="<%= local_assigns[:input].nil? ? String.new : input %>" name="level[inputs][]" allowed-pattern="[01]" auto-validate required>
	<paper-icon-button suffix onclick="clearInput()" icon="clear" alt="clear" title="clear"></paper-icon-button>
</paper-input>

app/views/levels/_level.html.erb
<paper-card>
	<div class="card-content">
		<h3><%= link_to level.name, level %></h3>
		<div><%= level.description %></div>
		<div><strong>Size:</strong> <%= level.width %> x <%= level.height %></div>
		<div>
			<strong>By,</strong>
			<%= link_to level.user do %>
				<%= level.user.name %>
			<% end %>
		</div>
	</div>
	<% if current_user == level.user || current_user.admin %>
		<div class="card-actions">
			<div class="horizontal justified">
				<%= link_to level do %>
					<paper-icon-button icon="info"></paper-icon-button>
				<% end %>
				<%= link_to edit_level_path(level), remote: true do %>
					<paper-icon-button icon="create"></paper-icon-button>
				<% end %>
				<%= link_to level, method: :delete, data: { confirm: 'Are you sure?' } do %>
					<paper-icon-button icon="delete"></paper-icon-button>
				<% end %>
			</div>
		</div>
	<% end %>
</paper-card>

app/views/levels/_output.html.erb
<paper-input label="Output" id="level_output" value="<%= local_assigns[:output].nil? ? String.new : output %>" name="level[outputs][]" allowed-pattern="[01]" auto-validate required>
	<paper-icon-button suffix onclick="clearInput()" icon="clear" alt="clear" title="clear"></paper-icon-button>
</paper-input>

app/views/levels/edit.html.erb
<h1> Editing Level </h1>

<%= render 'form', level: @level %>

app/views/levels/index.html.erb
<h1>Levels</h1>

<%= render @levels %>

<%= link_to new_level_path, class: "add-fab", remote: :true do %>
	<paper-fab icon="add"></paper-fab>
<% end %>

app/views/levels/new.html.erb
<h1> New Level </h1>

<%= render 'form', level: @level %>

app/views/levels/show.html.erb
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
		<title>TruBool</title>
		<%= csrf_meta_tags %>
		<meta name="theme-color" content="#000">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<!-- <link rel="manifest" href="/manifest.json"> -->
		<script src="/components/webcomponentsjs/webcomponents.min.js"></script>
		<link rel="import" href="/components/iron-icons/iron-icons.html">

		<link rel="import" href="/components/paper-button/paper-button.html">
		<link rel="import" href="/components/paper-icon-button/paper-icon-button.html">
		<link rel="import" href="/components/paper-item/paper-item.html">
		<link rel="import" href="/components/paper-listbox/paper-listbox.html">

		<link rel="import" href="/components/app-layout/app-drawer-layout/app-drawer-layout.html">
		<link rel="import" href="/components/app-layout/app-drawer/app-drawer.html">
		<link rel="import" href="/components/app-layout/app-header-layout/app-header-layout.html">
		<link rel="import" href="/components/app-layout/app-header/app-header.html">
		<link rel="import" href="/components/app-layout/app-toolbar/app-toolbar.html">
		<%= stylesheet_link_tag 'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= stylesheet_link_tag 'game', media: 'all', is: 'custom-style' %>
		<%= javascript_include_tag 'game' %>
		<%= render "layouts/styles" %>
		<%= render "levels/game-styles" %>
	</head>
	<body unresolved>
		<app-drawer-layout id="paperDrawerPanel" force-narrow>
			<app-drawer swipe-open>
				<%= render "layouts/drawercontent" %>
			</app-drawer>
			<div main>
				<canvas height="2160" width="3840"></canvas>
				<paper-button id="test" onclick="testSolution()" raised>Test</paper-button>
				<paper-icon-button id="menu-toggle" icon="menu" drawer-toggle></paper-icon-button>
			</div>
		</app-drawer-layout>
		<div id="game_board">
			<div class="width"><%= @level.width %></div>
			<div class="height"><%= @level.height %></div>
			<% for input in @level.inputs %>
				<div class="input">
					<% for num in input.split '' %>
						<div><%= num %></div>
					<% end %>
				</div>
			<% end %>
			<% for output in @level.outputs %>
				<div class="output">
					<% for num in output.split '' %>
						<div><%= num %></div>
					<% end %>
				</div>
			<% end %>
			<div class="pieces">
				<% for piece in @level.pieces %>
					<div><%= piece %></div>
				<% end %>
			</div>
		</div>
	</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<% for user in @users %>
	<paper-card>
		<div class="card-content">
			<h3><%= link_to user.name, user, remote: true %></h3>
			<img src="<%= user.picture_scale 128 %>" alt="<%= user.name %>" class="user_image" />
		</div>
	</paper-card>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% for level in @user.levels %>
	<%= render partial: 'levels/level', locals: { level: level } %>
<% end %>